#!/usr/bin/env bash
# ==============================================================================
# run_parameter_sweep.sh
#
# Runs AthenaK simulations for a sweep over parameter pairs (shear velocity & cold gas fraction).
# For each parameter pair, runs:
#   1. HR_build using MPI for resolution 512x256 (nx1=256, nx2=512)
#   2. lr_build for resolution 32x16 (nx1=16, nx2=32)
#   3. subgrid_model build for resolution 32x16 (nx1=16, nx2=32)
#
# Model Retraining Policy:
#   - Does NOT retrain the neural network model.
#   - Uses pre-trained model weights from default path: outputs/model_saves/pdf_model_saves
#
# Folder Structure:
#   simulation_outputs/sweeps/vshear_<V>_coldfrac_<F>/
#       ├── hr_build_512x256/
#       ├── lr_build_32x16/
#       ├── subgrid_model_32x16/
#       └── logs/
# ==============================================================================

set -euo pipefail

# ==============================================================================
# EASY TO TINKER PARAMETERS (TINKER AT TOP OF SCRIPT)
# ==============================================================================

# List of total shear velocities v_shear (in code units) to sweep over.
# In zero-momentum frame with rho_hot=0.001 & rho_cold=0.1:
#   vx_hot = v_shear / 1.1
#   vx_cold = -0.1 * vx_hot
# Example: v_shear = 31.09183 -> vx_hot = 28.2653, vx_cold = -2.82653
SHEAR_VELOCITIES=(31.09183)

# List of cold gas volume fractions (cold_frac) to sweep over.
COLD_FRACS=(0.5)

# Simulation time limit (tlim in Myr) - can be overridden via environment variable
TLIM="${TLIM:-10.0}"

# Number of MPI processes for HR_build (512x256) - can be overridden via environment variable
NUM_MPI_PROCS="${NUM_MPI_PROCS:-16}"

# Base directory for saving simulation output folders - can be overridden via environment variable
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_BASE_DIR="${OUTPUT_BASE_DIR:-${PROJECT_ROOT}/simulation_outputs/sweeps}"

# Pre-trained model directory (default model path; retraining disabled)
DEFAULT_MODEL_DIR="${PROJECT_ROOT}/outputs/model_saves/pdf_model_saves"

# Virtual environment python path
VENV_ACTIVATE="${PROJECT_ROOT}/venv/bin/activate"

# ==============================================================================
# HELPER FUNCTIONS
# ==============================================================================

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

separator() {
    echo "========================================================================"
}

check_builds() {
    log "Checking binary executables..."
    local missing=0

    if [[ ! -x "${PROJECT_ROOT}/builds/hr_build_mpi/src/athena" ]]; then
        log "ERROR: HR MPI binary not found at ${PROJECT_ROOT}/builds/hr_build_mpi/src/athena"
        missing=1
    fi
    if [[ ! -x "${PROJECT_ROOT}/builds/hr_build/src/athena" ]]; then
        log "ERROR: LR binary not found at ${PROJECT_ROOT}/builds/hr_build/src/athena"
        missing=1
    fi
    if [[ ! -x "${PROJECT_ROOT}/builds/subgrid_model/src/athena" ]]; then
        log "ERROR: Subgrid binary not found at ${PROJECT_ROOT}/builds/subgrid_model/src/athena"
        missing=1
    fi

    if [[ ${missing} -eq 1 ]]; then
        log "Please compile the builds before running this script."
        exit 1
    fi
    log "All binary executables verified successfully."
}

generate_athinput() {
    local target_file="$1"
    local job_name="$2"
    local nx1="$3"
    local nx2="$4"
    local mb_nx1="$5"
    local mb_nx2="$6"
    local ism_cooling="$7"
    local user_srcs="$8"
    local nscalars="$9"
    local vx_hot="${10}"
    local vx_cold="${11}"
    local cold_frac="${12}"
    local ndiag="${13}"

    cat <<EOF > "${target_file}"
# Athena++ (Kokkos version) input file generated by run_parameter_sweep.sh

<comment>
problem   = Kelvin-Helmholtz instability

<job>
basename = ${job_name}

<mesh>
nghost    = 3
nx1       = ${nx1}
x1min     = -5.0
x1max     =  5.0
ix1_bc    = periodic
ox1_bc    = periodic

nx2       = ${nx2}
x2min     = -10.0
x2max     =  10.0
ix2_bc    = reflect
ox2_bc    = user

nx3       = 1
x3min     = -0.5
x3max     = 0.5
ix3_bc    = periodic
ox3_bc    = periodic

<meshblock>
nx1       = ${mb_nx1}
nx2       = ${mb_nx2}
nx3       = 1

<time>
evolution  = dynamic
integrator = rk2
cfl_number = 0.4
nlim       = -1
tlim       = ${TLIM}
ndiag      = ${ndiag}

<hydro>
eos         = ideal
reconstruct = plm
rsolver     = hllc
nscalars    = ${nscalars}
gamma       = 1.666667
ism_cooling = ${ism_cooling}
hrate       = 0

<problem>
iprob     = 1
amp       = 0.01
sigma     = 0.25
vx_hot    = ${vx_hot}
vx_cold   = ${vx_cold}
a_char    = 0.0625
rho_cold  = 0.1
rho_hot   = 0.001
press     = 13.925145161290322
cold_frac = ${cold_frac}
EOF

    if [[ "${user_srcs}" == "true" ]]; then
        echo "user_srcs = true" >> "${target_file}"
    fi

    cat <<EOF >> "${target_file}"

<units>
length_cgs = 3.08568e+18
mass_cgs   = 4.91417e+31
time_cgs   = 3.15576e+13
mu         = 0.62

<output1>
file_type = hst
dt        = 0.01

<output2>
file_type = bin
variable  = hydro_w
dt        = 0.01

<output3>
file_type = bin
variable  = hydro_u
dt        = 0.01

<output4>
file_type = rst
dt        = 1.0
EOF
}

# ==============================================================================
# MAIN EXECUTION
# ==============================================================================

check_builds

# Environment setup
if [[ -f "${VENV_ACTIVATE}" ]]; then
    # shellcheck source=/dev/null
    source "${VENV_ACTIVATE}"
    log "Activated python venv: ${VENV_ACTIVATE}"
else
    log "WARNING: Virtual environment not found at ${VENV_ACTIVATE}"
fi

export MODEL_SAVES_DIR="${DEFAULT_MODEL_DIR}"
log "Default pre-trained model directory: ${MODEL_SAVES_DIR}"
log "Retraining: OFF (using existing model weights)"

separator
log "STARTING PARAMETER SWEEP"
log "Shear Velocities : ${SHEAR_VELOCITIES[*]}"
log "Cold Gas Fracs   : ${COLD_FRACS[*]}"
log "Time Limit (tlim): ${TLIM} Myr"
log "MPI Processes    : ${NUM_MPI_PROCS}"
separator

for v_shear in "${SHEAR_VELOCITIES[@]}"; do
    for cold_frac in "${COLD_FRACS[@]}"; do
        # Calculate vx_hot and vx_cold in zero-momentum frame
        # v_shear = vx_hot - vx_cold; vx_cold = -0.1 * vx_hot => v_shear = 1.1 * vx_hot
        vx_hot=$(python3 -c "print(f'{$v_shear / 1.1:.6f}')")
        vx_cold=$(python3 -c "print(f'{-0.1 * ($v_shear / 1.1):.6f}')")

        pair_name="vshear_${v_shear}_coldfrac_${cold_frac}"
        pair_dir="${OUTPUT_BASE_DIR}/${pair_name}"
        log_dir="${pair_dir}/logs"

        hr_dir="${pair_dir}/hr_build_512x256"
        lr_dir="${pair_dir}/lr_build_32x16"
        sg_dir="${pair_dir}/subgrid_model_32x16"

        mkdir -p "${hr_dir}" "${lr_dir}" "${sg_dir}" "${log_dir}"

        separator
        log "Processing parameter pair: v_shear=${v_shear} (vx_hot=${vx_hot}, vx_cold=${vx_cold}), cold_frac=${cold_frac}"
        log "Output folder: ${pair_dir}"
        separator

        # ----------------------------------------------------------------------
        # 1. HR Simulation (512x256, MPI)
        # ----------------------------------------------------------------------
        hr_athinput="${pair_dir}/hr_512x256.athinput"
        generate_athinput "${hr_athinput}" "KH_HR_512x256" \
            128 256 32 64 "true" "false" 1 "${vx_hot}" "${vx_cold}" "${cold_frac}" 100

        log "Running 1/3: HR_build (512x256, MPI with ${NUM_MPI_PROCS} processes)..."
        mpirun -np "${NUM_MPI_PROCS}" \
            "${PROJECT_ROOT}/builds/hr_build_mpi/src/athena" \
            -i "${hr_athinput}" \
            -d "${hr_dir}" \
            > "${log_dir}/hr_build_512x256.log" 2>&1
        log "HR_build simulation finished. Log: ${log_dir}/hr_build_512x256.log"

        # ----------------------------------------------------------------------
        # 2. LR Simulation (32x16, ISM cooling)
        # ----------------------------------------------------------------------
        lr_athinput="${pair_dir}/lr_32x16.athinput"
        generate_athinput "${lr_athinput}" "KH_LR_32x16" \
            16 32 16 32 "true" "false" 2 "${vx_hot}" "${vx_cold}" "${cold_frac}" 100

        log "Running 2/3: lr_build (32x16, ISM cooling)..."
        "${PROJECT_ROOT}/builds/hr_build/src/athena" \
            -i "${lr_athinput}" \
            -d "${lr_dir}" \
            > "${log_dir}/lr_build_32x16.log" 2>&1
        log "lr_build simulation finished. Log: ${log_dir}/lr_build_32x16.log"

        # ----------------------------------------------------------------------
        # 3. Subgrid Model Simulation (32x16, PyTorch model)
        # ----------------------------------------------------------------------
        sg_athinput="${pair_dir}/subgrid_32x16.athinput"
        generate_athinput "${sg_athinput}" "KH_SG_32x16" \
            16 32 16 32 "false" "true" 2 "${vx_hot}" "${vx_cold}" "${cold_frac}" 5

        log "Running 3/3: subgrid_model build (32x16, pre-trained CNN model)..."
        (
            export PYTHONPATH="${PROJECT_ROOT}:${PROJECT_ROOT}/data:${PROJECT_ROOT}/models/conv_nn:${PROJECT_ROOT}/builds/subgrid_model/src:${PYTHONPATH:-}"
            export MODEL_SAVES_DIR="${DEFAULT_MODEL_DIR}"
            cd "${PROJECT_ROOT}/builds/subgrid_model/src"
            ./athena \
                -i "${sg_athinput}" \
                -d "${sg_dir}" \
                > "${log_dir}/subgrid_model_32x16.log" 2>&1
        )
        log "subgrid_model simulation finished. Log: ${log_dir}/subgrid_model_32x16.log"

        # ----------------------------------------------------------------------
        # 4. Diagnostic Visualizations (density animation & profiles using ergane)
        # ----------------------------------------------------------------------
        log "Generating diagnostic visualizations (density animation & profiles)..."
        python3 "${PROJECT_ROOT}/shell_scripts/visualize_sweeps.py" "${pair_dir}" \
            > "${log_dir}/visualize_sweeps.log" 2>&1
        log "Visualizations saved: density_animation.mp4 & profiles_perpendicular.png"

        log "Successfully completed parameter pair: ${pair_name}"
    done
done

separator
log "ALL PARAMETER SWEEP SIMULATIONS COMPLETED SUCCESSFULLY"
log "Outputs saved under: ${OUTPUT_BASE_DIR}"
separator
